# add your desired knowledge graph components here

# protein:
#     represented_as: node
#     preferred_id: uniprot
#     label_in_input: uniprot_protein

# disease:
#     represented_as: node
#     preferred_id: doid
#     label_in_input: do_disease
    
# protein interaction:
#     is_a: pairwise molecular interaction
#     represented_as: edge
#     label_in_input: protein_protein_interaction

# protein to disease association:
#     is_a: association
#     represented_as: edge
#     label_in_input: protein_disease_association


## I think the preferred id and properties need to be in line with HGNC

###############
# Nodes
###############

gene:
    represented_as: node
    preferred_id: ensembl
    label_in_input: gene
    properties:
        external_gene_name: str
        ensembl_peptide_id: str

# cell type needs to be associated with tissue
cell type:
    represented_as: node
    preferred_id: cl
    label_in_input: cell_type # this means giving it a node labeled as cell_type it will become a cell type node
    # it cannot map to exact CL ids because I need to give all the CL labels (node id) here
    # open an issue for feature request
    is_a: cell  # biolink 
    properties:
        cell_type_name: str
        cell_ontology_id: str
        tissue_name: str
        uberon_tissue_id: str
        broad_type: str
        broad_type_2: str
        broad_type_3: str


species:
    represented_as: node
    preferred_id: ncbitaxon
    label_in_input: species
    is_a: cellular organism  # biolink 
    properties:
        species_scientific_name: str


orthologous group:
    represented_as: node
    preferred_id: eggnog
    label_in_input: orthologous_group
    is_a: gene family # biolink 
    properties:
        eggnog_dataset_name: str # at which layer the orhologous group is calculated, e.g. mammalia; eukaryota...
        eggnog_dataset_id: str

###############
# Associations
###############
gene in orthologous group:
    represented_as: edge
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: gene to gene family association
    label_in_input: gene_in_orthologous_group
    source: Gene # this syntax for biochatter select relationships, "pascalcase"
    target: OrthologousGroup

gene from species:
    represented_as: edge
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: association
    label_in_input: gene_from_species
    source: Gene
    target: Species

cell type from species:
    represented_as: edge
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: association
    label_in_input: cell_type_from_species
    source: CellType
    target: Species

gene enriched in cell type:
    represented_as: edge
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: association
    label_in_input: gene_enriched_in_cell_type
    source: Gene
    target: CellType

gene enhanced in cell type:
    represented_as: edge
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: association
    label_in_input: gene_enhanced_in_cell_type
    source: Gene
    target: CellType

gene low specificity in species:
    represented_as: edge 
    is_relationship: true
    present_in_knowledge_graph: true
    is_a: association
    label_in_input: gene_low_specificity_in_species
    source: Gene
    target: Species